
# Install snaps
- name: Install 
  snap:
    name:
      - bitwarden
      - docker
      - chromium
      - codium
      - figma-linux
      - terraform
      - tor
      - vlc
  become: true

# Install a snap with classic confinement
- name: Install snaps with option --classic
  snap:
    name:
      - go
      - kotlin
      - codium
    classic: yes
  become: true

# Install a snap with from a specific channel
# - name: Install snaps with option --channel=latest/edge
# snap:
# name:
# - node
# channel: latest/edge
# become: true

# Install snap with classic and edge
- name: Install snaps with option --channel=latest/edge and classic
  snap:
    name:
      - node
    channel: latest/edge
    classic: yes
  become: true
