
    # tap homebrew 
    # install chunkwm and skhd
    
    # if custom dotfile is found for either than link them in their proper
    # place
 
- name: Install packages
  include_role:
    name: geerlingguy.homebrew

- name: Symlink yabai Config
  file:
    src: "{{ ansible_env.HOME }}/Repos/dotfiles/yabairc"
    dest: "{{ ansible_env.HOME }}/.yabairc"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    state: link

- name: +x chunkwmrc
  file:
    dest: "{{ ansible_env.HOME }}/Repos/dotfiles/yabairc"
    mode: +x

- name: Symlink skhd Config
  file:
    src: "{{ ansible_env.HOME }}/Repos/dotfiles/skhdrc"
    dest: "{{ ansible_env.HOME }}/.skhdrc"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    state: link

- name: Start chunkwm
  command: brew services start yabai

- name: Start skhd 
  command: brew services start skhd


  
