
- apt_repository:
    repo: "ppa:mmstick76/alacritty"

- apt_repository:
    repo: "ppa:ubuntu-mozilla-daily/ppa" 

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Install a list of packages
  apt:
    pkg:
    - firefox-trunk
    - alacritty
    - vim
    - zsh
    - wireguard
    - virtualbox
    - tmux
    - ffmpeg
    - openvpn 
    - dialog 
    - python3-pip 
    - python3-setuptools
    - vagrant
    - python3
    - openssl
    - libssl-dev
  become: true
