
-   
    name: Arch Desktop Configuration
    hosts: localhost
    tasks:
        - name: Create directories for git repositories
          file:
            path: '{{ ansible_env.HOME }}\Repos'
            state: directory
            mode: '0755'

        - name: Install packages
          include_role:
              name: pacman

        - name: Install rust
          include_role:
            name: rust
