
- 
  name: MacOS Desktop Configuration
  hosts: localhost
  vars:
    - login_shell: /usr/local/bin/zsh
    - dotfiles: jonaylor89/dotfiles
  pre_tasks:
    - name: Pull Configurations
      file: 
        path: '{{ ansible_env.HOME }}/Repos'
        state: directory
    # Create ssh keys for github
  tasks: 
   - name: Dotfiles
     git: 
      repo: 'https://github.com/{{ dotfiles }}.git'
      dest: '{{ ansible_env.HOME }}/Repos/dotfiles'
      update: yes

   - name: OSX Config
     include_role:
        name: osx

   - name: Install rust
     include_role:
        name: rust

  # - name: Link Configs
  # file: 
        
   - name: Install oh-my-zsh
     git: 
       repo: https://github.com/robbyrussell/oh-my-zsh.git 
       dest: '{{ ansible_env.HOME }}/.local/share/oh-my-zsh'
       update: yes

   - name: Install oh-my-fish
     git: 
       repo: https://github.com/oh-my-fish/oh-my-fish.git 
       dest: '{{ ansible_env.HOME }}/.local/share/omf'
       update: yes

   - name: Install tmux plugin manager
     git: 
       repo: https://github.com/tmux-plugins/tpm.git 
       dest: '{{ ansible_env.HOME }}/.local/share/tpm'
       update: yes

   - name: Install dein.vim
     git: 
       repo: https://github.com/Shougo/dein.vim.git 
       dest: '{{ ansible_env.HOME }}/.cache/dein/repos/github.com/Shougo/dein.vim'
       update: yes

       # - name: Symlink Config Files
       # file:
       # src: ""
       # dest: ""
       # state: link

   - name: Window Manager 
     include_role:
       name: yabai

   - name: Package Manager
     include_role:
       name: homebrew

  - name: Python Package Manager
     include_role:
       name: pip

   - block:
      - name: check if homebrew bash is installed
        stat: 
          path: /usr/local/bin/bash
        register: brew_bash

      - name: add homebrew bash to /etc/shells
        lineinfile: 
          dest: /etc/shells 
          line: "/usr/local/bin/bash" 
          state: present
        when: brew_bash.stat.exists

      - name: check if homebrew zsh is installed
        stat: 
          path: /usr/local/bin/zsh
        register: brew_zsh

      - name: add homebrew zsh to /etc/shells
        lineinfile: 
          dest: /etc/shells 
          line: "/usr/local/bin/zsh" 
          state: present
        when: brew_zsh.stat.exists

      - name: check if homebrew fish is installed
        stat: 
          path: /usr/local/bin/fish
        register: brew_fish

      - name: add homebrew fish to /etc/shells
        lineinfile: 
          dest: /etc/shells 
          line: "/usr/local/bin/fish" 
          state: present
        when: brew_fish.stat.exists

     when: ansible_os_family == "Darwin"
     become: yes

   - name: check if preferred login_shell is installed
     stat: path={{ login_shell }}
     register: login_shell_installed

   - name: Set default shell
     user: 
       name: "{{ ansible_user_id }}" 
       shell: "{{ login_shell }}"
     when: login_shell_installed.stat.exists
     become: yes

   - name: Specify iTerm preferences directory 
     command: defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/Repos/dotfiles/iterm2"

   - name: Tell iTerm to use custom preferences 
     command: defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true



