
- name: install rustup
  shell: curl https://sh.rustup.rs -ssf | sh -s -- -y --no-modify-path --default-toolchain nightly
  args:
    warn: false

- name: install rustfmt, clippy
  command: rustup component add {{ item }}
  with_items:
  - rustfmt
  - clippy
