
- name: install rustup
  shell: curl https://sh.rustup.rs -ssf | sh -s -- -y --no-modify-path --default-toolchain nightly
  args:
    warn: false

- name: install rustfmt, clippy
  command: "{{ ansible_env.HOME }}/.cargo/bin/rustup component add {{ item }}"
  with_items:
  - rustfmt
  - clippy

- name: install cargo
  command: "{{ ansible_env.HOME }}/.cargo/bin/cargo install {{ item }}"
  with_items:
  - eza
